### ISSUE TITLE
The 'pan_evap' data is not properly wrote to prms data file

### ISSUE THREAD

**Issue by sinloss** [pygsflow/pygsflow#42]
Hi, all!

Recently I use the `PrmsData` class to compose my weather data, the `tmax` and `tmin`  columns are properly wrote to the *prms data file* but the `pan_evap` column somehow is missing. 

**Additional information**:
* All the valid data columns are properly appended with the `_0`.
* There's no exception thrown.

**Comment by jlarsen-usgs** [comment]
@sinloss thanks for raising this issue and putting in a PR to fix it.
