### ISSUE TITLE
Parameter 'Width' Integers Not Required in Parameter File 

### ISSUE THREAD

**Issue by mrush-usgs** [pygsflow/pygsflow#6]
prms_parameter.py currently prints the parameter 'width' attribute (default 10) to the parameter file. These numbers are not required for prms/gsflow. 

https://github.com/pygsflow/pygsflow/blob/master/gsflow/prms/prms_parameter.py

Lines 535 and 584

**Comment by jlarsen-usgs** [comment]
Closing this issue, because it does not affect GSFLOW's performance and allows users to run PRMS independently using the same parameter files.
