### ISSUE TITLE
remove_record() method does not recognize parameter names 

### ISSUE THREAD

**Issue by mrush-usgs** [pygsflow/pygsflow#7]
I am trying to remove parameters from the control file. 

I can get_record(name='soilzone_module'):

####
soilzone_module
1
4
soilzone
####

But I can't remove_record(name='soilzone_module'):

/home/mrush/miniconda3/lib/python3.8/site-packages/gsflow/param_base.py:211: UserWarning: The record does not exist: soilzone_module
  warnings.warn("The record does not exist: {}".format(name),

**Comment by jlarsen-usgs** [comment]
@mrush-usgs 
This is most likely a case sensitivity issue. I just pushed an update to force all of these methods to be case insensitive. Give the updated version a test and let me know if it works.

**Comment by jlarsen-usgs** [comment]
@mrush-usgs 
my first solution introduced an unexpected bug; I've updated it again. Please check the most recent version of the code out.
